file: solda_config.yaml
lista_programas:
- diam_cord: 6.0
  estrategia: offsets conectados
  nome: Padrao offsets
  p_desligamento: 700
  p_religamento: 2000
  reg_associada: Contornos
  sobrep_cord: 50.0
  tensao: 16.6
  vel_desloc: 360.0
  wire_speed: 3.6
- diam_cord: 5.8
  estrategia: offsets conectados
  nome: Xaropada dos offsets
  p_desligamento: 700
  p_religamento: 2000
  reg_associada: Contornos
  sobrep_cord: 52.0
  tensao: 16.6
  vel_desloc: 360.0
  wire_speed: 3.6
- diam_cord: 6
  estrategia: zigzags vai-e-volta
  nome: internos acelerados
  p_desligamento: 700
  p_religamento: 2000
  reg_associada: Areas Largas
  sobrep_cord: 50
  tensao: 16.6
  vel_desloc: 425
  wire_speed: 3.6
- diam_cord: 6.0
  estrategia: linha medial continua
  nome: Padrao como offsets
  p_desligamento: 700
  p_religamento: 2000
  reg_associada: Thin Walls
  sobrep_cord: 50.0
  tensao: 16.6
  vel_desloc: 360.0
  wire_speed: 3.6
- diam_cord: 6.0
  estrategia: weaving
  nome: Parecido com offsets
  p_desligamento: 700
  p_religamento: 2000
  reg_associada: Estrangulamentos
  sobrep_cord: 50.0
  tensao: 16.6
  vel_desloc: 420.0
  wire_speed: 3.6
- diam_cord: 6.0
  estrategia: sfdsf
  nome: fdfsf
  p_desligamento: 700
  p_religamento: 2000
  reg_associada: Areas Largas
  sobrep_cord: 50.0
  tensao: 16.6
  vel_desloc: 420.0
  wire_speed: 3.6
