from __future__ import annotations
import copy
import datetime
import numpy as np
import concurrent.futures
from cv2 import imread
from functools import wraps
from typing import TYPE_CHECKING
from components import images_tools as it, path_tools
from components import morphology_tools as mt
from components.thin_walls import ThinWallRegions
from components.offset import OffsetRegions
from components.zigzag import ZigZagRegions
from components.bottleneck import BridgeRegions
from components.timer import Timer
from components.path_tools import Path
from components import points_tools as pt

if TYPE_CHECKING:
    from components.files import System_Paths

    # from components.zigzag import ZigZag
    from typing import List


class Island:
    def __init__(self, *args, **kwargs):
        self.name: str
        self.img = []
        self.thin_walls: ThinWallRegions
        self.offsets: OffsetRegions
        self.bridges: BridgeRegions
        self.zigzags: ZigZagRegions
        self.rest_of_picture_f1 = []
        self.rest_of_picture_f2 = []
        self.rest_of_picture_f3 = []
        self.ext_start = []
        self.int_start = []
        self.external_tree_route: List[Path] = []
        self.internal_tree_route: List[Path] = []
        self.thinwalls_tree_route: List[Path] = []
        self.island_route: List[Path] = []
        self.prohibited_areas = []
        self.macro_areas_weaved = []
        self.jumps = []
        self.regions = []
        if args:
            self.name = args[0]
            self.img = args[1]
        if kwargs:
            for key, value in kwargs.items():
                setattr(self, key, value)
        return


class Layer:
    """Each of the layers generated by the slicing process in the treatment of 3D models"""

    def __init__(self, **kwargs):
        self.name: int
        self.original_img: np.ndarray
        self.odd_layer: int = 0
        self.dpi: int = 0
        self.base_frame = []
        self.program_tw: str = ""
        self.program_cont: str = ""
        self.program_larg: str = ""
        self.program_bridg: str = ""
        self.layer_height: float = 0
        self.diam_tw_real: float = 0
        self.diam_cont_real: float = 0
        self.diam_larg_real: float = 0
        self.diam_bridg_real: float = 0
        self.first_layer_height: float = 0
        self.first_diam_tw_real: float = 0
        self.first_diam_cont_real: float = 0
        self.first_diam_larg_real: float = 0
        self.first_diam_bridg_real: float = 0
        self.path_radius_tw: float = 0
        self.path_radius_cont: float = 0
        self.path_radius_bridg: float = 0
        self.path_radius_larg: float = 0
        self.path_radius_int_ext: float = 0
        self.first_path_radius_tw: float = 0
        self.first_path_radius_cont: float = 0
        self.first_path_radius_bridg: float = 0
        self.first_path_radius_larg: float = 0
        self.first_path_radius_int_ext: float = 0
        self.sob_tw_per: float = 0
        self.sob_cont_per: float = 0
        self.sob_larg_per: float = 0
        self.sob_bridg_per: float = 0
        self.sob_int_ext_per: float = 0
        self.pxl_per_mm: float = 0
        self.mm_per_pxl: float = 0
        self.islands: List[Island]
        self.selected = []
        self.layer_final_path = []
        if kwargs:
            for key, value in kwargs.items():
                setattr(self, key, value)

    def close_final_path(self, folders: System_Paths):
        folders.load_islands_hdf5(self)
        for island in self.islands:
            folders.load_offsets_hdf5(self.name, island)
            folders.load_island_paths_hdf5(self.name, island)
            itr = island.internal_tree_route
            etr = island.external_tree_route
            twtr = island.thinwalls_tree_route
            with Timer("  Creating island route img"):
                if etr.sequence == []:
                    print("   No external route found")
                    pass
                else:
                    if not itr.sequence == []:
                        itr.sequence = [list(x) for x in itr.sequence]
                    if not etr.sequence == []:
                        etr.sequence = [list(x) for x in etr.sequence]
                    if not twtr.sequence == []:
                        twtr.sequence = [list(x) for x in twtr.sequence]
                    island_route_path_for_img = (
                        etr.sequence + itr.sequence + twtr.sequence
                    )
                    island_island_route_img = it.points_to_img(
                        island_route_path_for_img, np.zeros(self.base_frame)
                    )

            with Timer("  Connecting all parts"):
                internal_simpl = path_tools.simplifica_retas_masterV2(
                    itr.sequence, 0.002, itr.jumps
                )
                external_simpl = path_tools.simplifica_retas_masterV2(
                    etr.sequence, 0.002, etr.jumps
                )
                thinwalls_simpl = path_tools.simplifica_retas_masterV2(
                    twtr.sequence, 0.002, twtr.jumps
                )
                island_route_path = external_simpl + internal_simpl + thinwalls_simpl
                island_island_route_img = it.chain_to_lines(
                    island_route_path, np.zeros(self.base_frame)
                )
                if self.odd_layer == 1:
                    print("   Layer Rotated 90 degrees")
                    etr.sequence = path_tools.rotate_path_odd_layer(
                        external_simpl, self.base_frame
                    )
                    itr.sequence = path_tools.rotate_path_odd_layer(
                        internal_simpl, self.base_frame
                    )
                    twtr.sequence = path_tools.rotate_path_odd_layer(
                        thinwalls_simpl, self.base_frame
                    )
                    island_route_path = path_tools.rotate_path_odd_layer(
                        island_route_path, self.base_frame
                    )
                    island_island_route_img = it.chain_to_lines(
                        island_route_path,
                        np.zeros([self.base_frame[1], self.base_frame[0]]),
                    )
                island.regions = [itr.regions + etr.regions + twtr.regions]
                island.jumps = [itr.jumps + etr.jumps + twtr.jumps]
                island.island_route = Path(
                    "island_route",
                    island_route_path,
                    island.regions,
                    jumps=island.jumps,
                    img=island_island_route_img,
                )

        if not isinstance(self.islands, list):
            self.islands = [self.islands]
        final_sequence = []
        for island in self.islands:
            pth = island.island_route.sequence
            final_sequence.extend(pth)
        final_jumps = []
        for island in self.islands:
            jps = island.island_route.jumps
            final_jumps.extend(jps)
        final_regions = []
        for island in self.islands:
            rgns = island.island_route.regions
            final_regions.extend(rgns)
        final_sequence_img = it.chain_to_lines(
            final_sequence, np.zeros(self.base_frame)
        )

        if self.odd_layer == 1:
            print("   Layer Rotated 90 degrees")
            final_sequence = path_tools.rotate_path_odd_layer(
                final_sequence, self.base_frame
            )
            final_sequence_img = it.chain_to_lines(
                final_sequence,
                np.zeros([self.base_frame[1], self.base_frame[0]]),
            )
            if len(final_jumps[0]) > 0:
                final_jumps = path_tools.rotate_path_odd_layer(
                    final_jumps[0], self.base_frame
                )

        self.layer_final_path = Path(
            "layer_final_route",
            final_sequence,
            final_regions,
            img=final_sequence_img,
            jumps=final_jumps,
        )

        with Timer("  Saving route images"):
            folders.save_final_routes_hdf5(self)
        return

    def close_routes_external(self, folders: System_Paths):
        with Timer("  Connecting external routes"):
            folders.load_islands_hdf5(self)
            for isl in self.islands:
                folders.load_offsets_hdf5(self.name, isl)
                folders.load_zigzags_hdf5(self.name, isl)
                folders.load_bridges_hdf5(self.name, isl)
                folders.load_thin_walls_hdf5(self.name, isl)
                if isl.offsets.regions == []:
                    with Timer(" Only TW"):
                        isl.external_tree_route = Path(
                            "OnlyTW",
                            path_tools.img_to_chain(
                                isl.thin_walls.regions[0].route.astype(np.uint8)
                            )[0],
                        )
                        isl.external_tree_route.get_regions(isl)
                else:
                    with Timer(" Connecting Offset bridges"):
                        isl.external_tree_route = path_tools.connect_offset_bridges(
                            isl,
                            self.base_frame,
                            mt.make_mask(self, "3_4_cont"),
                            self.path_radius_cont,
                            self.sob_cont_per,
                        )
                    with Timer("  Conecting pontes de Crossover bridges"):
                        isl.external_tree_route = path_tools.connect_cross_over_bridges(
                            isl
                        )
                        isl.ext_start = isl.external_tree_route.sequence[0]
                isl.external_tree_route.get_img(self.base_frame)
        with Timer("  Saving route images"):
            folders.save_external_routes_hdf5(self.name, self.islands)
        return

    def close_routes_internal(self, folders: System_Paths):
        folders.load_islands_hdf5(self)
        for isl in self.islands:
            folders.load_bridges_hdf5(self.name, isl)
            folders.load_zigzags_hdf5(self.name, isl)
            folders.load_offsets_hdf5(self.name, isl)
            folders.load_thin_walls_hdf5(self.name, isl)
            with Timer("  Connecting neighboring zigzags"):
                isl.internal_tree_route = path_tools.start_internal_route(
                    isl, mt.make_mask(self, "full_larg"), self.path_radius_larg
                )
            if isl.internal_tree_route != []:
                with Timer("  Connecting zigzag bridges"):
                    isl.internal_tree_route = path_tools.connect_zigzag_bridges(isl)
                    isl.internal_tree_route.get_img(self.base_frame)
            else:
                print("   No internal routes found")
                isl.internal_tree_route = Path("0", [], [])
        with Timer("  Saving route images"):
            folders.save_internal_routes_hdf5(self.name, self.islands)
        return

    def close_routes_thinwalls(self, folders: System_Paths):
        folders.load_islands_hdf5(self)
        for isl in self.islands:
            folders.load_thin_walls_hdf5(self.name, isl)
            with Timer("  Converting thin walls"):
                isl.thinwalls_tree_route = path_tools.connect_thin_walls(
                    isl, self.path_radius_cont
                )
                isl.thinwalls_tree_route.get_img(self.base_frame)

        with Timer("  Saving route images"):
            folders.save_thinwall_final_routes_hdf5(self.name, self.islands)

    def create_layers(
        folders: System_Paths,
        path_input: str,
        file_name: str,
        dpi: int,
        layer_height: float,
        first_layer_height: float,
    ):
        """
        :param folders: System_Paths: object with the paths to save and load files
        :path_input: str: path for the file to be sliced
        :file_name: str: name of the file
        :param dpi: int: Density of pixels per inch for the image generation
        :layer_height: float: height of each layer
        :param first_layer_height: float: height of the first layer

        :return: List[Layer]: list of Layer objects created from the input file

        Creates Layer objects from the input file, slicing 3D models if necessary
            3D models are sliced into layers using the call_slicer function from the folders object. The slicer was developed in another reseach by Minetto et al. (2023).
            2D images are directly converted into Layer objects.
        Each layer image recieves a border using the img_add_border function from the images_tools module and is rotated if it is an odd layer.
        Afterwards, each layer is divided into islands using the divide_islands function.
        The object is then saved using the save_layers and save_folders_structure functions from the folders object.
        The format of the saved file is HDF5, which allows for efficient storage and retrieval of large datasets.
        """

        def divide_islands(layer: Layer):
            img = layer.original_img
            separated_imgs, labels, num = it.divide_by_connected(img)
            layer.islands_number = num
            islands = []
            for i, si in enumerate(separated_imgs):
                islands.append(Island(f"I_{i:03d}", si))
            layer.islands = islands
            return

        list_layers = []
        with Timer("  Creating layers"):
            if file_name.endswith(".stl") or file_name.endswith(".STL"):
                # 3D model
                hdf5_file_name = file_name.rsplit("/", 1)[-1]
                hdf5_file_name = hdf5_file_name.replace(".stl", "")
                hdf5_file_name = hdf5_file_name.replace(".STL", "")
                list_layers = folders.call_slicer(
                    file_name, path_input, dpi, layer_height, first_layer_height
                )
            else:
                # 2D image
                hdf5_file_name = file_name.rsplit("/", 1)[-1]
                hdf5_file_name = hdf5_file_name.replace(".pgm", "")
                layer = Layer()
                img = imread(path_input, 0)
                layer.make_input_img("L_000", img, dpi, 0, first_layer_height, 1)
                list_layers = [layer]
            # Dividing islands
            for layer in list_layers:
                divide_islands(layer)

        with Timer("  Saving layers"):
            ts = datetime.datetime.now()
            folders.save_layers(f"{hdf5_file_name}_{ts.date()}", list_layers)
            folders.save_folders_structure(f"{hdf5_file_name}_{ts.date()}")
        return

    def connect_zigzags(self, folders: System_Paths):

        def parallelizando(func):
            @wraps(func)
            def wrapper(*args):
                processed_isl = []
                with concurrent.futures.ThreadPoolExecutor() as executor:
                    if [*args]:
                        results = [
                            executor.submit(func, island, *args)
                            for island in self.islands
                        ]
                    else:
                        results = [
                            executor.submit(func, island) for island in self.islands
                        ]
                    for l in concurrent.futures.as_completed(results):
                        processed_isl.append(l.result())
                    processed_isl.sort(key=lambda x: x.name)
                    self.islands = processed_isl

            return wrapper

        @parallelizando
        def make_island_graph(island: Island) -> Island:
            if np.sum(island.rest_of_picture_f3) > 0:
                if hasattr(island, "zigzags"):
                    island.zigzags.make_graph(
                        island.bridges.zigzag_bridges, self.base_frame
                    )
            return island

        @parallelizando
        def get_island_linked_zigzags(island: Island) -> Island:
            if np.sum(island.rest_of_picture_f3) > 0:
                for zb in island.bridges.zigzag_bridges:
                    zb.get_linked_zigzags(island.zigzags.regions)
            return island

        for isl in self.islands:
            folders.load_bridges_hdf5(self.name, isl)
        with Timer("  Creating region graphs"):
            make_island_graph()
        with Timer("  Connecting Zigzag bridges"):
            get_island_linked_zigzags()

        for isl in self.islands:
            if hasattr(isl, "zigzags"):
                isl.zigzags.connect_island_zigzags(
                    self.path_radius_larg,
                    mt.make_mask(self, "full_larg"),
                    self.base_frame,
                )

        with Timer("  Saving graphs"):
            zigzags_path = f"/{self.name}/{isl.name}/zigzags"
            for isl in self.islands:
                if hasattr(isl, "zigzags"):
                    folders.save_graph_hdf5(
                        zigzags_path, f"zigzags_graph", isl.zigzags.zigzags_graph
                    )
                    folders.save_img_hdf5(
                        zigzags_path, f"all_zigzags", isl.zigzags.all_zigzags
                    )
                    folders.save_img_hdf5(
                        zigzags_path, f"macro_areas", isl.zigzags.macro_areas
                    )
                if hasattr(isl, "bridges"):
                    if hasattr(isl.bridges, "zigzag_bridges"):
                        for bridge in isl.bridges.zigzag_bridges:
                            folders.save_props_hdf5(
                                f"/{self.name}/{isl.name}/bridges/zigzag_bridges/{bridge.name}",
                                bridge.__dict__,
                            )
        return

    def internal_weaving(self, internal_weaving, folders: System_Paths):
        with Timer("  Generating internal weavings"):
            folders.load_islands_hdf5(self)
            for isl in self.islands:
                folders.load_offsets_hdf5(self.name, isl)
                folders.load_bridges_hdf5(self.name, isl)
                folders.load_zigzags_hdf5(self.name, isl)
                folders.load_thin_walls_hdf5(self.name, isl)
                if hasattr(isl, "zigzags"):
                    original_macro_areas_weaved = []
                    original_all_zigzags = copy.deepcopy(isl.zigzags.all_zigzags)
                    isl.zigzags.macro_areas_weaved, isl.zigzags.all_zigzags = (
                        isl.zigzags.create_oscilatory_inner(
                            isl.zigzags.macro_areas,
                            self.original_img,
                            self.base_frame,
                            self.path_radius_larg,
                            mt.make_mask(self, "full_larg"),
                            isl.zigzags.regions,
                            isl.bridges,
                            isl.offsets.regions,
                            isl.thin_walls.regions,
                            internal_weaving,
                        )
                    )
                    if np.sum(isl.zigzags.all_zigzags) == 0:
                        isl.zigzags.all_zigzags = original_all_zigzags
                        print("   Something whent wrong, restoring all zigzags")
                    if np.sum(isl.zigzags.macro_areas_weaved) == 0:
                        isl.zigzags.macro_areas_weaved = original_macro_areas_weaved
                        print("   Something whent wrong, restoring macro areas weaved")

        with Timer("  Saving routes"):
            for isl in self.islands:
                if hasattr(isl, "zigzags"):
                    folders.save_img_hdf5(
                        f"/{self.name}/{isl.name}/zigzags",
                        f"all_zigzags",
                        isl.zigzags.all_zigzags,
                    )
                    folders.delete_item_hdf5(
                        f"/{self.name}/{isl.name}/zigzags/macro_areas"
                    )
                    folders.save_img_hdf5(
                        f"/{self.name}/{isl.name}/zigzags",
                        f"macro_areas",
                        isl.zigzags.macro_areas,
                    )
                    folders.delete_item_hdf5(
                        f"/{self.name}/{isl.name}/zigzags/macro_areas_weaved"
                    )
                    folders.save_img_hdf5(
                        f"/{self.name}/{isl.name}/zigzags",
                        f"macro_areas_weaved",
                        isl.zigzags.macro_areas_weaved,
                    )
        return

    def islands_path_starts(self, folders: System_Paths):
        folders.load_islands_hdf5(self)
        for island in self.islands:
            folders.load_offsets_hdf5(self.name, island)
            folders.load_zigzags_hdf5(self.name, island)
            folders.load_bridges_hdf5(self.name, island)
            with Timer("  Finding the ext-int union point"):
                # if hasattr(island, "zigzags") and hasattr(island, "offsets"):
                if len(island.offsets.regions) > 0:
                    if hasattr(island, "zigzags"):
                        if len(island.zigzags.regions) > 0:
                            island.ext_start, island.int_start = (
                                path_tools.connect_internal_external(
                                    island, self.path_radius_int_ext
                                )
                            )
                    else:
                        # if hasattr(island, "offsets"):
                        island.ext_start = pt.img_to_points(
                            island.offsets.regions[0].route.astype(np.uint8)
                        )[0]
                        island.int_start = []
                print("   " + str(island.ext_start))
                with Timer("  saving route images"):
                    folders.save_props_hdf5(
                        f"/{self.name}/{island.name}",
                        island.__dict__,
                        ext_start=island.ext_start,
                        int_start=island.int_start,
                    )
        return

    def make_input_img(
        self,
        name: str,
        img,
        dpi: int,
        odd_layer: bool,
        layer_height: float,
        n_layers: int,
    ):
        """Uses the file paths to import the images, converts them to binary,
        and creates a Layer object for each."""
        self.name = name
        img_w_b = it.img_add_border(img)
        if odd_layer:
            img_w_b = it.rotate_img_cw(img_w_b)
            self.odd_layer = 1
        self.dpi = dpi
        self.base_frame = img_w_b.shape
        self.n_layers = n_layers
        self.layer_height = layer_height
        self.original_img = img_w_b
        return

    def make_thin_walls(
        self,
        folders: System_Paths,
        d_tw: float,
        sob_tw_per: float,
        name_prog: str,
    ) -> None:

        def make_islands_thinWalls(island: Island) -> List[Island, dict]:
            """
            :param island: each separated body on the layer: Island
            :return: islands with the ThinWals regions mapped: List[Island]
            """
            island_img = folders.load_img_hdf5(f"/{self.name}/{island.name}", "img")
            island.thin_walls = ThinWallRegions()
            island.thin_walls.make_thin_walls(
                island_img,
                self.base_frame,
                self.path_radius_tw,
            )
            return island

        def check_islands_thinWalls(island: Island, mm_per_pxl) -> List[Island, dict]:
            island_img = folders.load_img_hdf5(f"/{self.name}/{island.name}", "img")
            if len(island.thin_walls.regions) > 0:
                island.thin_walls.check_thin_walls(
                    island_img,
                    self.path_radius_tw,
                )
            return island

        self.pxl_per_mm = self.dpi / 25.4
        self.program_tw = name_prog
        self.mm_per_pxl = 1 / self.pxl_per_mm
        d_tw_pxl = d_tw * self.pxl_per_mm
        self.sob_tw_per = sob_tw_per
        self.path_radius_tw = round(d_tw_pxl * 0.5)
        self.diam_tw_real = d_tw
        for isl in self.islands:
            folders.create_new_hdf5_group(f"/{self.name}/{isl.name}/thin_walls")

        with Timer("  Creating thin walls"):
            processed_regions: List[Island] = []
            with concurrent.futures.ThreadPoolExecutor() as executor:
                results = [
                    executor.submit(make_islands_thinWalls, island)
                    for island in self.islands  # self.islands
                ]
                for l in concurrent.futures.as_completed(results):
                    processed_regions.append(l.result())
            processed_regions.sort(key=lambda x: x.name)
            self.islands = processed_regions

        with Timer("  Checking thin walls"):
            processed_regions: List[Island] = []
            with concurrent.futures.ThreadPoolExecutor() as executor:
                results = [
                    executor.submit(check_islands_thinWalls, island, self.mm_per_pxl)
                    for island in self.islands  # self.islands
                ]
                for l in concurrent.futures.as_completed(results):
                    processed_regions.append(l.result())
            processed_regions.sort(key=lambda x: x.name)
            self.islands = processed_regions

        with Timer("  Removing thin walls from the layer"):
            for island in self.islands:
                island.rest_of_picture_f1 = copy.deepcopy(self.original_img)
                for reg in island.thin_walls.regions:
                    island.rest_of_picture_f1 = it.image_subtract(
                        island.rest_of_picture_f1, reg.img
                    )

        with Timer("  Saving images of the regions"):
            folders.save_regs_thinwalls_hdf5(self.name, self.islands)
            folders.save_props_hdf5(f"/{self.name}", self.__dict__)
        return

    def make_thin_wall_routes(self, folders: System_Paths):
        with Timer("  Creating thin wall routes"):
            folders.load_islands_hdf5(self)
            for isl in self.islands:
                folders.load_thin_walls_hdf5(self.name, isl)
                isl.thin_walls.make_routes_tw(self.path_radius_tw, self.sob_tw_per)
        with Timer("  Saving route images"):
            for isl in self.islands:
                for reg in isl.thin_walls.regions:
                    folders.save_img_hdf5(
                        f"/{self.name}/{isl.name}/thin_walls/{reg.name}",
                        "route",
                        reg.route.astype(bool),
                    )
                    folders.save_img_hdf5(
                        f"/{self.name}/{isl.name}/thin_walls/{reg.name}",
                        "trail",
                        reg.trail.astype(bool),
                    )
        return

    def make_offsets(
        self,
        folders: System_Paths,
        void_max: float,
        external_max: int,
        internal_max: int,
        d_cont: float,
        sob_cont_per: float,
        name_prog: str,
    ) -> None:

        def parallelizando(func):
            @wraps(func)
            def wrapper(*args):
                processed_isl = []
                with concurrent.futures.ThreadPoolExecutor() as executor:
                    if [*args]:
                        results = [
                            executor.submit(func, island, *args)
                            for island in self.islands
                        ]
                    else:
                        results = [
                            executor.submit(func, island) for island in self.islands
                        ]
                    for l in concurrent.futures.as_completed(results):
                        processed_isl.append(l.result())
                    processed_isl.sort(key=lambda x: x.name)
                    self.islands = processed_isl

            return wrapper

        @parallelizando
        def load_and_make_levels(island: Island) -> Island:
            island.offsets = OffsetRegions()
            rest_of_picture_f1 = folders.load_img_hdf5(
                f"{self.name}/{island.name}", "rest_of_picture_f1"
            )
            rest_in_this_island = np.logical_and(rest_of_picture_f1, island.img)
            if np.sum(rest_in_this_island) > 0:
                folders.load_thin_walls_hdf5(self.name, island)
                island.offsets.create_levels(
                    rest_in_this_island,
                    mt.make_mask(self, "full_cont"),
                    mt.make_distancer(
                        self, region="cont", percentage=self.sob_cont_per
                    ),
                    self.name,
                    island.name,
                    self.original_img,
                    island.thin_walls,
                )
            return island

        @parallelizando
        def create_loops_in_island(island: Island) -> Island:
            rest_of_picture_f1 = folders.load_img_hdf5(
                f"/{self.name}/{island.name}", "rest_of_picture_f1"
            )
            rest_in_this_island = np.logical_and(rest_of_picture_f1, island.img)
            if np.sum(rest_in_this_island) > 0:
                for level in island.offsets.levels:
                    if level.name == "Lvl_000":
                        level.create_loops(
                            mt.make_mask(self, "full_cont"),
                            self.base_frame,
                            rest_in_this_island,
                            self.path_radius_cont,
                            island.offsets.hybrid_offset_tw,
                        )
                    else:
                        level.create_loops(
                            mt.make_mask(self, "full_cont"),
                            self.base_frame,
                            self.path_radius_cont,
                            rest_in_this_island,
                        )
            return island

        @parallelizando
        def create_influence_regions_in_island(island: Island) -> Island:
            rest_of_picture_f1 = folders.load_img_hdf5(
                f"/{self.name}/{island.name}", "rest_of_picture_f1"
            )
            rest_in_this_island = np.logical_and(rest_of_picture_f1, island.img)
            if np.sum(rest_in_this_island) > 0:
                island.offsets.create_influence_regions(self.base_frame)
            return island

        @parallelizando
        def calculate_island_voids(island: Island):
            rest_of_picture_f1 = folders.load_img_hdf5(
                f"/{self.name}/{island.name}", "rest_of_picture_f1"
            )
            rest_in_this_island = np.logical_and(rest_of_picture_f1, island.img)
            if np.sum(rest_in_this_island) > 0:
                island.offsets.calculate_voids(
                    self.base_frame,
                    rest_in_this_island,
                    island.offsets.levels,
                    island.offsets.n_levels,
                    self.path_radius_cont,
                )
            return island

        @parallelizando
        def make_regions_in_islands(island: Island) -> Island:
            rest_of_picture_f1 = folders.load_img_hdf5(
                f"/{self.name}/{island.name}", "rest_of_picture_f1"
            )
            rest_in_this_island = np.logical_and(rest_of_picture_f1, island.img)
            if np.sum(rest_in_this_island) > 0:
                island.rest_of_picture_f2 = island.offsets.make_regions(
                    rest_in_this_island,
                    self.base_frame,
                    self.path_radius_cont,
                    self.void_max,
                    self.max_external_walls,
                    self.max_internal_walls,
                    np.sum(mt.make_mask(self, "full_cont")),
                )
            return island

        @parallelizando
        def make_island_valid_loops(island: Island) -> Island:
            rest_of_picture_f1 = folders.load_img_hdf5(
                f"/{self.name}/{island.name}", "rest_of_picture_f1"
            )
            rest_in_this_island = np.logical_and(rest_of_picture_f1, island.img)
            if np.sum(rest_in_this_island) > 0:
                island.offsets.all_valid_loops = island.offsets.make_valid_loops(
                    self.base_frame
                )
            return island

        self.program_cont = name_prog
        d_cont_pxl = d_cont * self.pxl_per_mm
        self.sob_cont_per = sob_cont_per
        self.path_radius_cont = round(d_cont_pxl * 0.5)
        self.diam_cont_real = d_cont
        self.void_max = void_max
        self.max_external_walls = external_max
        self.max_internal_walls = internal_max
        for isl in self.islands:
            folders.create_new_hdf5_group(f"/{self.name}/{isl.name}/offsets")

        with Timer("  Creating offset levels"):
            load_and_make_levels()

        with Timer("  Creating loops"):
            create_loops_in_island()

        with Timer("  Creating influence regions"):
            create_influence_regions_in_island()

        with Timer("  Creating Offset regions"):
            calculate_island_voids()

        with Timer("  Removing regions from the layer"):
            make_regions_in_islands()

        with Timer("  Reunindo todos os loops em uma unica imagem"):
            make_island_valid_loops()

        with Timer("  Saving region images"):
            folders.save_regs_offsets_hdf5(self.name, self.islands)
            folders.save_props_hdf5(f"/{self.name}", self.__dict__)
        return

    def make_offset_routes(self, amendment_size, folders: System_Paths, outer_spiral):
        folders.load_islands_hdf5(self)
        for isl in self.islands:
            folders.load_offsets_hdf5(self.name, isl)
            isl.offsets.make_routes_o(
                self.base_frame,
                mt.make_mask(self, "full_cont"),
                self.path_radius_cont,
                amendment_size,
                outer_spiral,
            )
        with Timer("  Saving routes images"):
            for isl in self.islands:
                # if np.sum(isl.rest_of_picture_f2) > 0:
                # if len(isl.rest_of_picture_f2) != 0:
                if hasattr(isl, "offsets"):
                    for reg in isl.offsets.regions:
                        folders.save_img_hdf5(
                            f"/{self.name}/{isl.name}/offsets/{reg.name}",
                            "route",
                            reg.route.astype(bool),
                        )
                        folders.save_img_hdf5(
                            f"/{self.name}/{isl.name}/offsets/{reg.name}",
                            "trail",
                            reg.trail.astype(bool),
                        )
        folders.save_props_hdf5(f"/{self.name}", self.__dict__)

    def make_bridges(
        self,
        folders: System_Paths,
        n_max: float,
        d_bridg: float,
        sob_bridg_per: float,
        n_layers: int,
        sum_prohibited_areas,
        name_prog: str,
        connect_offsets: int,
    ):

        def parallelizando(func):
            @wraps(func)
            def wrapper(*args):
                processed_isl = []
                with concurrent.futures.ThreadPoolExecutor() as executor:
                    if [*args]:
                        results = [
                            executor.submit(func, island, *args)
                            for island in self.islands
                        ]
                    else:
                        results = [
                            executor.submit(func, island) for island in self.islands
                        ]
                    for l in concurrent.futures.as_completed(results):
                        processed_isl.append(l.result())
                    processed_isl.sort(key=lambda x: x.name)
                    self.islands = processed_isl

            return wrapper

        @parallelizando
        def make_islands_offset_bridges(island: Island) -> Island:
            # folders.load_offsets_hdf5(self.name, isl)
            try:
                rest_of_picture_f2 = folders.load_img_hdf5(
                    f"/{self.name}/{island.name}", "rest_of_picture_f2"
                )
                island.offsets_graph, island.offsets_mst = (
                    island.bridges.make_offset_bridges(
                        rest_of_picture_f2,
                        isl.offsets,
                        self.base_frame,
                        self.path_radius_cont,
                        rest_of_picture_f2,
                        sum_prohibited_areas,
                    )
                )
            except:
                pass
            return island

        @parallelizando
        def make_islands_zigzag_bridges(island: Island) -> Island:
            folders.load_offsets_hdf5(self.name, isl)
            rest_of_picture_f2 = folders.load_img_hdf5(
                f"/{self.name}/{island.name}", "rest_of_picture_f2"
            )
            if np.sum(rest_of_picture_f2) > 0:
                island.bridges.make_zigzag_bridges(
                    rest_of_picture_f2,
                    self.base_frame,
                    self.path_radius_bridg,
                    n_max,
                    isl.offsets.regions,
                )
            return island

        @parallelizando
        def make_islands_cross_over_bridges(island: Island) -> Island:
            try:
                self.n_max = n_max
                island.bridges.all_bridges = island.bridges.make_cross_over_bridges(
                    sum_prohibited_areas, island.offsets_mst
                )
            except:
                pass
            return island

        self.program_bridg = name_prog
        self.n_max = n_max
        self.diam_bridg_real = d_bridg
        self.sob_bridg_per = sob_bridg_per
        d_bridg_pxl = d_bridg * self.pxl_per_mm
        self.path_radius_bridg = round(d_bridg_pxl * 0.5)
        distancer = mt.make_distancer(self, "bridg", sob_bridg_per)
        folders.save_props_hdf5(f"/{self.name}", self.__dict__)
        folders.load_islands_hdf5(self)
        for isl in self.islands:
            isl.bridges = BridgeRegions()
        if self.name == "L_000":
            self.prohibited_areas = np.zeros_like(self.original_img)

        # removing areas outside the contours
        folders.load_offsets_hdf5(self.name, isl)
        if connect_offsets == 1:
            with Timer("  Creating Offset bridges"):
                make_islands_offset_bridges()

        with Timer("  Creating Zigzag bridges"):
            make_islands_zigzag_bridges()

        with Timer("  Creating Crossover bridges"):
            make_islands_cross_over_bridges()

        with Timer("  Removing bridges from layer"):
            for island in self.islands:
                rest_of_picture_f2 = folders.load_img_hdf5(
                    f"/{self.name}/{island.name}", "rest_of_picture_f2"
                )
                island.rest_of_picture_f3 = island.bridges.apply_bridges(
                    rest_of_picture_f2, self.base_frame
                )
        last_prohibited_areas = np.zeros_like(self.original_img)
        with Timer("  Generating prohibited areas"):
            if not int(self.name[2:]) == n_layers:
                for isl in self.islands:
                    for reg in isl.bridges.offset_bridges:
                        last_prohibited_areas = np.logical_or(
                            last_prohibited_areas, reg.img
                        )
                    for reg in isl.bridges.cross_over_bridges:
                        last_prohibited_areas = np.logical_or(
                            last_prohibited_areas, reg.img
                        )

        with Timer("  Saving region images"):
            folders.save_regs_bridges_hdf5(self.name, self.islands)
            folders.save_img_hdf5(
                f"/{self.name}", "prohibited_areas", self.prohibited_areas
            )
        return last_prohibited_areas

    def make_bridges_routes(self, folders: System_Paths, sob_int_ext_per):
        folders.load_islands_hdf5(self)
        self.sob_int_ext_per = sob_int_ext_per
        mask_distancer = mt.make_distancer(self, "int_ext", percentage=sob_int_ext_per)
        internal_mask_dist = mt.make_distancer(
            self, "bridg", percentage=self.sob_bridg_per
        )
        for isl in self.islands:
            folders.load_bridges_hdf5(self.name, isl)
            folders.load_offsets_hdf5(self.name, isl)
            if hasattr(isl, "bridges"):
                isl.bridges.make_routes_b(
                    isl.offsets.regions,
                    self.path_radius_cont,
                    self.path_radius_bridg,
                    mask_distancer,
                    internal_mask_dist,
                    self.base_frame,
                    isl.rest_of_picture_f2,
                )
            with Timer("  Saving routes images"):
                folders.save_routes_bridges_hdf5(self.name, self.islands)
                folders.save_props_hdf5(f"/{self.name}", self.__dict__)

    def make_zigzags(
        self,
        folders: System_Paths,
        d_larg: float,
        sob_larg_per: float,
        name_prog: str,
        w_style: int,
    ):

        def parallelizando(func):
            @wraps(func)
            def wrapper(*args):
                processed_isl = []
                with concurrent.futures.ThreadPoolExecutor() as executor:
                    if [*args]:
                        results = [
                            executor.submit(func, island, *args)
                            for island in self.islands
                        ]
                    else:
                        results = [
                            executor.submit(func, island) for island in self.islands
                        ]
                    for l in concurrent.futures.as_completed(results):
                        processed_isl.append(l.result())
                    processed_isl.sort(key=lambda x: x.name)
                    self.islands = processed_isl

            return wrapper

        @parallelizando
        def find_islands_monotonic(island: Island) -> Island:
            island.rest_of_picture_f3 = folders.load_img_hdf5(
                f"/{self.name}/{island.name}", "rest_of_picture_f3"
            )
            rest_of_picture_f2 = folders.load_img_hdf5(
                f"/{self.name}/{island.name}", "rest_of_picture_f2"
            )
            import components.skeleton as sk

            sem_galhos, sem_galhos_dist, trunks = sk.create_prune_divide_skel(
                rest_of_picture_f2.astype(np.uint8), 0
            )
            # medial_transform = island.bridges.medial_transform
            ideal_sum = np.sum(mt.make_mask(self, "full_larg"))
            if np.sum(island.rest_of_picture_f3) > 0:
                island.zigzags.find_monotonic(
                    island.rest_of_picture_f3,
                    self.base_frame,
                    self.path_radius_larg,
                    sem_galhos,
                    sem_galhos_dist,
                    trunks,
                    island.bridges.zigzag_bridges,
                    w_style,
                    ideal_sum,
                )
            return island

        self.program_larg = name_prog
        self.diam_larg_real = d_larg
        self.sob_larg_per = sob_larg_per
        d_larg_pxl = d_larg * self.pxl_per_mm
        self.path_radius_larg = round(d_larg_pxl * 0.5)
        folders.save_props_hdf5(f"/{self.name}", self.__dict__)
        folders.load_islands_hdf5(self)
        for island in self.islands:
            folders.load_bridges_hdf5(self.name, island)
            island.zigzags = ZigZagRegions()
        with Timer("  Finding monotonic regions"):
            find_islands_monotonic()
        with Timer("  Finding monotonic regions"):
            find_islands_monotonic()
        with Timer("  Saving monotonic regions images"):
            folders.save_regs_zigzags_hdf5(self.name, self.islands)
            folders.save_props_hdf5(f"/{self.name}", self.__dict__)
        return

    def make_zigzag_routes(self, folders: System_Paths, style, sob_int, sob_out):
        folders.load_islands_hdf5(self)
        # mask_distancer_internal = mt.make_distancer(self, "int_ext", percentage=sob_int)
        sob_inwards = sob_int
        for isl in self.islands:
            with Timer(f"  Generating zigzag routes, Layer:{self.name}"):
                folders.load_zigzags_hdf5(self.name, isl)
                if hasattr(isl, "zigzags"):
                    isl.zigzags.make_routes_z(
                        self.base_frame,
                        self.path_radius_larg,
                        sob_inwards,
                        sob_out,
                        style,
                    )

        with Timer("  Saving images of zigzag routes"):
            folders.save_regs_zigzags_hdf5(self.name, self.islands)
            folders.save_props_hdf5(f"/{self.name}", self.__dict__)
        return
